version: '3.8'

name: secondzip

services:
  mysql:
    image: mysql:8.0
    container_name: secondzip-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: secondzip
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: secondzip-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    profiles:
      - backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: secondzip-backend
    restart: always

    env_file:
      - ../backend/src/main/resources/.env

    environment:
      DB_URL: jdbc:log4jdbc:mysql://mysql:3306/secondzip
      REDIS_HOST: redis
      REDIS_PORT: 6379

    ports:
      - '8080:8080'

    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  # ==========================
  # Frontend
  # ==========================
  frontend:
    image: ghcr.io/second-zip/second-zip-frontend:latest
    container_name: secondzip-frontend
    restart: always

    ports:
      - '80:80'
      - '443:443'

    volumes:
      - /var/www/certbot:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  mysql-data:
  redis-data:
